# Generated by Django 5.2.1 on 2025-05-31 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'db_table': 'artista',
            },
        ),
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(db_column='proprietario')),
                ('album', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='music_library.album')),
                ('artist', models.ForeignKey(db_column='artista_id', on_delete=django.db.models.deletion.CASCADE, to='music_library.artist')),
            ],
            options={
                'db_table': 'artista_album',
                'unique_together': {('artist', 'album')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titolo', max_length=200)),
                ('author', models.CharField(db_column='autore', max_length=100)),
                ('participating_artists', models.CharField(blank=True, db_column='artisti_partecipanti', max_length=255, null=True)),
                ('duration', models.CharField(blank=True, db_column='durata', max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('file_name', models.TextField(blank=True, db_column='file_name', null=True)),
                ('variant', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], db_column='variant')),
                ('play_count', models.IntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, db_column='album_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_library.album')),
            ],
            options={
                'db_table': 'traccia',
                'unique_together': {('id', 'variant')},
            },
        ),
    ]
