# Generated by Django 5.2.1 on 2025-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
        migrations.AlterField(
            model_name='track',
            name='file_name',
            field=models.TextField(db_column='file_name'),
        ),
    ]
