# Generated by Django 5.2.1 on 2025-06-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_remove_track_file_alter_track_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
    ]
